### PR TITLE
Updated the loader

### PR DESCRIPTION
**Pull request by Ansh101112**
## Related Issue
#87 

## Description
Updated the loader UI of website ad also fixed bugs of website for better and faster user experience too.

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots: 
Screenshot (126)

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Reviewers:
@aryasoni98

### CODE REVIEW

**Comment by aryasoni98** [comment]
@Ansh101112 Why you raise another PR .

**Comment by aryasoni98** [comment]
@Ansh101112 

Diagnosis: The build failure is due to a type error in the file home.tsx at line 19, where the parameter newItem is implicitly typed as any.

Solution: To resolve this issue, explicitly define the type of newItem in the handleItemDrop function. Update the function signature like this:

const handleItemDrop = (newItem: ItemType) => {
  // Function body
};
Replace ItemType with the appropriate type for newItem in your code. This explicit typing will prevent the type error and allow the build to succeed.

**Comment by Ansh101112** [comment]
> @Ansh101112 Why you raise another PR .

sir i have created a new pr for this because of the some error coming up during diagnosing the bug i main branch that's why i have created a new branch dev with new pr.

**Comment by Ansh101112** [comment]
> @Ansh101112
> 
> Diagnosis: The build failure is due to a type error in the file home.tsx at line 19, where the parameter newItem is implicitly typed as any.
> 
> Solution: To resolve this issue, explicitly define the type of newItem in the handleItemDrop function. Update the function signature like this:
> 
> const handleItemDrop = (newItem: ItemType) => { // Function body }; Replace ItemType with the appropriate type for newItem in your code. This explicit typing will prevent the type error and allow the build to succeed.

okay sir i will do this.

**Comment by aryasoni98** [comment]
> > @Ansh101112 Why you raise another PR .
> 
> sir i have created a new pr for this because of the some error coming up during diagnosing the bug i main branch that's why i have created a new branch dev with new pr.

Close the PR and also not push the code on master.

**Comment by Ansh101112** [comment]
> > > @Ansh101112 Why you raise another PR .
> > 
> > sir i have created a new pr for this because of the some error coming up during diagnosing the bug i main branch that's why i have created a new branch dev with new pr.
> 
> Close the PR and also not push the code on master. 

Previous pr na?

**Comment by aryasoni98** [comment]
> > > > @Ansh101112 Why you raise another PR .
> > > 
> > > 
> > > sir i have created a new pr for this because of the some error coming up during diagnosing the bug i main branch that's why i have created a new branch dev with new pr.
> > 
> > 
> > Close the PR and also not push the code on master.
> 
> Previous pr na?

Yes close the preview PR

**Pull request closed without merging**
