### PR TITLE
bugfix: Login and Signup is not working

### LINKED ISSUE #62: [bug]: Login and Signup is not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

facing problem with login and signup 
Screenshot 2024-02-18 162911
Screenshot 2024-02-18 163032

### Steps to reproduce

1.Verify the functionality of the login and signup processes.
2.Test the login and signup functionalities.

### Environment

None

### Version

Local

### Repository

InfraBoard

### PR DESCRIPTION
**Pull request by Divesh-Suryavanshi**
closes #62
### Identified Issue
During signup, the code unexpectedly checks for `userId` and `secret` before a user is even created. This check seems intended for email verification but is happening at the wrong stage, causing errors.

### Temporary Fix
To prevent the error, a section of code in `signupPage.tsx` responsible for this check has been commented out. However, this is not a permanent solution.

### Next Steps
1. **Dedicated Verification Page:** Create a new page named `verifyEmail.tsx` specifically for handling email verification. This page will allow users to enter the userId and Secret received in their verification email.

### CODE REVIEW

**Comment by shivajee98** [comment]
Could you share the screenshots after successful sign up and login to the page?

**Comment by Divesh-Suryavanshi** [comment]
> Could you share the screenshots after successful sign up and login to the page?

yes sure, i already have the screenshots which i forgot to attach with the description while making a pull request:-

1. User enters the details requested and then clicks on register
Screenshot 2024-03-09 031024


2. After registration user gets automatically logged in to the platform
Screenshot 2024-03-09 031103

**Comment by aryasoni98** [comment]
@Divesh-Suryavanshi Check the build code. Build is failed .

**Review by aryasoni98 — APPROVED** [review]

**Comment by shivajee98** [comment]
@Divesh-Suryavanshi  still facing issue to login.

**Pull request merged**
