### PR TITLE
loader updated

### PR DESCRIPTION
**Pull request by Ansh101112**
## Description

Updated the loader and add a new and better UI-designed loader for a better user experience.

closing issue: #87 

## Summary by CodeRabbit

- **New Features**
  - Integrated `ClockLoader` and `BarLoader` from `react-spinners` for improved loading animations across the app.

- **Enhancements**
  - Updated loading animations on the Home, Login, and Signup pages for a more consistent and visually appealing experience.

- **Bug Fixes**
  - Improved error handling within the login process to ensure smoother user experience during authentication.

### CODE REVIEW

**Comment by aryasoni98** [comment]
Screenshot 2024-05-22 at 9 53 10 AM

**Comment by Ansh101112** [comment]
> Screenshot 2024-05-22 at 9 53 10 AM
> 

??

**Comment by Ansh101112** [comment]
@aryasoni98 sir please see it for review and give an update on it asap.

**Comment by aryasoni98** [comment]
> @aryasoni98 sir please see it for review and give an update on it asap.

check the error I share the log ss on commit . some function issue on Login and Home file .

**Comment by Ansh101112** [comment]
> > @aryasoni98 sir please see it for review and give an update on it asap.
> 
> check the error I share the log ss on commit . some function issue on Login and Home file . 

Okay sir will update this pr asap

**Pull request closed without merging**
